development:
  adapter: postgresql
  encoding: unicode
  database: landing_page_development
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: landing_page_production
  pool: 5
  username: landing_page
  password:
